gantt
    title Diagramme de Gantt
    dateFormat DD-MM-YYYY 
    section Pré-étude
        Début                       :milestone, 07-08-2023, 0d
        Planification               :a1, 07-08-2023, 4h
        Etude CDC                   :a2, after a1, 4h
        Etude syst. / Blocs         :a3, after a2, 1d
        Choix technologies          :a4, after a3, 1d
        Choix composants            :a5, after a4, 1d
        Concept firmware            :a6, after a5, 40h
        Fin de la pré-étude         :milestone, 12-08-2023, Od
    section Schéma
        Commencer schéma            :milestone, 14-08-2023, 0d
        Construction blocs          :b1, 12-08-2023, 4h
        Schéma principal            :b2, after b1, 4h
        Finir le schéma             :milestone, 19-08-2023, Od
    section PCB
        Commencer le PCB            :milestone, 21-08-2023, 0d
        Fin du PCB                  :milestone, 24-08-2023, 0d
        Commande du PCB             :milestone, 24-08-2023, Od
    section Programmation
    section Tests & mesu