%%{init: {'theme': 'forest', 'themeVariables': { 'fontSize': '200px', 'fontFamily': 'Arial'}}}%%

graph TB
    start{{"Start"}} --> cond1{"IMU measure to do & SD available"}
    cond1 -->|True| subcond1{LED enabled}
    cond1 -->|False| cond2{"GNSS measure to do & SD available"}
    subcond1 -->|True| A["Reset LED counter"]
    subcond1 -->|False| B["IMU data read routine"]
    A --> B["IMU data read routine"]
    B --> C["Update delta-time measure"]
    C --> subcond2{Detect acceleration > 2G}
    subcond2 -->|True| T["Flag important measure = 1"]
    subcond2 -->|False| D["Flag important measure = 0"]
    D & T --> subcond3{Detect acceleration}
    subcond3 -->|True| E["Reset inactive counter"]
    subcond3 -->|False| F["SD card schedule Write for IMU"]
    E --> F["SD card schedule Write IMU"]
    F --> G["IMU measure to do flag = 0"]
    G --> H["Update last measure time"]
    cond2 -->|True| I["SD card schedule Write GNSS"]
    cond2 -->|False| J["Reset comm status"]
    I --> K["GNSS measure to do flag = 0"]
    J --> L["LED blue OFF"]
    H --> cond3{Error Check}
    K --> cond3{Error Check}
    L --> cond3{Error Check}
    cond3 -->|True| M["LED red on"]
    cond3 -->|False| N["LED red off"]
    M & N --> O["SD card routine tasks"]
    O --> P["Button routine task"]
    P --> Q{Check inactivity}
    Q -->|True| QT["Shutdown system"]
    Q -->|False| Poll
    QT --> Poll["Poll for serial commands"]
    Poll --> final{{"End"}}
