sequenceDiagram
    participant Main as Main Loop (APP_Tasks)
    participant Timer as Timer Interrupt
    participant SD as SD Card Logger
    participant GNSS
    participant IMU
    participant USART

    Main->>+Main: Initialize appData.state = APP_STATE_INIT
    alt APP_STATE_INIT
        Main->>+IMU: Initialize IMU
        IMU-->>-Main: IMU Initialized
        Main->>+GNSS: Initialize GNSS
        GNSS-->>-Main: GNSS Initialized
        Main->>Main: appData.state = APP_STATE_CONFIG
    end

    alt APP_STATE_CONFIG
        Main->>+SD: Initialize SD Card parameters
        SD-->>-Main: SD Card Parameters Set
    end

    alt APP_STATE_LOGGING
        Timer->>+Main: stateTimer_callback()
        alt timeData.measTodo[BNO055_idx] == true
            Main->>+IMU: Read IMU data
            IMU-->>-Main: IMU Data Read
            Main->>+SD: Write IMU data
            SD-->>-Main: IMU Data Written
        end
        alt timeData.measTodo[GNSS_idx] == true
            Main->>+GNSS: Read GNSS data
            GNSS-->>-Main: GNSS Data Read
            Main->>+SD: Write GNSS data
            SD-->>-Main: GNSS Data Written
        end
        Main->>+SD: sd_fat_logging_task()
        SD-->>-Main: Logging Task Completed
        Main->>Main: btnTaskGest()
    end

    alt APP_STATE_COMM_LIVE_GNSS
        USART->>+Main: Receive command
        Main-->>-USART: Command Acknowledged
        USART-->>Main: 
        Main->>+GNSS: Display GNSS live data
        GNSS-->>-Main: GNSS Data Displayed
    end

    alt APP_STATE_COMM_LIVE_IMU
        Timer->>+Main: stateTimer_callback()
        Main->>+IMU: Read IMU data
        IMU-->>-Main: IMU Data Read
        Main->>+USART: Display IMU data
        USART-->>-Main: IMU Data Displayed
    end

    alt APP_STATE_CONFIGURATE_BBX
        USART->>+Main: Receive command
        Main-->>-USART: Command Acknowledged
        USART-->>Main: 
        Main->>+SD: Update Config
        SD-->>-Main: Config Updated
    end

    alt APP_STATE_SHUTDOWN
        Main->>Main: sys_shutdown()
    end
